{
 "title": "Fluent Bit",
 "tags": [ "fluent bit" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(fluentbit_input_records_total, host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "Record input rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{host=~\"$node\"}[$rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Record input rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "content": "The record input rate reflects the rate at which records enter the Fluent Bit pipeline. Lines should be relatively flat. Spikes indicate periods of unusually rapid logging, which may require investigation. "
  },
  {
   "title": "Record output rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{host=~\"$node\",name!=\"null.0\"}[$rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_total{host=~\"$node\",name!=\"null.0\"}[$rate_interval])) by (name)",
     "legendFormat": "{{name}} retries"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{host=~\"$node\",name!=\"null.0\"}[$rate_interval])) by (name)",
     "legendFormat": "{{name}} retries failed"
    }
   ]
  },
  {
   "title": "Record output rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "content": "The record output rate is the rate at which logs are written to an output. This panel shows failed writes, and failed retries. Occasional failed writes are acceptable. Failed retries indicate dropped logs and should be investigated. "
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{host=~\"$node\",name!=\"null.0\"}[$rate_interval])) by (name)",
     "legendFormat": "{{name}} errors"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "content": "The error rate panel shows the rate at which the log pipeline encounters failures while writing logs. The error rate for all output plugins should consistently be zero. Any spike in the error rate indicates dropped logs. "
  }
 ]
}