{
 "title": "Local Volume Provisioner",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(local_volume_provisioner_proctable_running, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Server requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "local_volume_provisioner_apiserver_requests_total{instance=~\"$instance\", method=\"create\"}",
     "legendFormat": "create requests"
    },
    {
     "expr": "local_volume_provisioner_apiserver_requests_total{instance=~\"$instance\", method=\"delete\"}",
     "legendFormat": "delete requests"
    },
    {
     "expr": "local_volume_provisioner_apiserver_requests_failed_total{instance=~\"$instance\", method=\"create\"}",
     "legendFormat": "failed create requests"
    },
    {
     "expr": "local_volume_provisioner_apiserver_requests_failed_total{instance=~\"$instance\", method=\"delete\"}",
     "legendFormat": "failed delete requests"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_volume_provisioner_apiserver_requests_duration_seconds_sum{instance=~\"$instance\", method=\"create\"}[1m]) / rate(local_volume_provisioner_apiserver_requests_duration_seconds_count{instance=~\"$instance\", method=\"create\"}[1m])",
     "legendFormat": "create requests"
    },
    {
     "expr": "rate(local_volume_provisioner_apiserver_requests_duration_seconds_sum{instance=~\"$instance\", method=\"delete\"}[1m]) / rate(local_volume_provisioner_apiserver_requests_duration_seconds_count{instance=~\"$instance\", method=\"delete\"}[1m])",
     "legendFormat": "delete requests"
    }
   ]
  },
  {
   "title": "Discovered volumes",
   "type": "graph",
   "description": "Discovered volumes per worker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "local_volume_provisioner_persistentvolume_discovery_total{instance=~\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average discovery duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_volume_provisioner_persistentvolume_discovery_duration_seconds_sum{instance=~\"$instance\"}[1m]) / rate(local_volume_provisioner_persistentvolume_discovery_duration_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "duration [s]"
    }
   ]
  },
  {
   "title": "Deleted volumes",
   "type": "graph",
   "description": "Deleted volumes per worker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "local_volume_provisioner_persistentvolume_delete_total{instance=~\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "local_volume_provisioner_persistentvolume_delete_failed_total{instance=~\"$instance\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Average delete duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_volume_provisioner_persistentvolume_delete_duration_seconds_sum{instance=~\"$instance\"}[1m]) / rate(local_volume_provisioner_persistentvolume_delete_duration_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "duration [s]"
    }
   ]
  },
  {
   "title": "Running proctables",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "local_volume_provisioner_proctable_running{instance=~\"$instance\"}",
     "legendFormat": "running"
    }
   ]
  }
 ]
}