apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: addons.kubeaddons.mesosphere.io
spec:
  group: kubeaddons.mesosphere.io
  names:
    kind: Addon
    plural: addons
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            chartReference:
              properties:
                release:
                  type: string
                repo:
                  type: string
                chart:
                  type: string
                values:
                  type: string
            manifest:
              type: string
