---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: awsebscsiprovisioner
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: awsebscsiprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    appversion.kubeaddons.mesosphere.io/awsebscsiprovisioner: "0.4.0"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  namespace: kube-system
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    chart: awsebscsiprovisioner
    repo: https://mesosphere.github.io/charts/stable
    version: 0.2.9
    values: |
      ---
      resizer:
        enabled: false
      snapshotter:
        enabled: true
      provisioner:
        enableVolumeScheduling: true
      storageclass:
        isDefault: true
