---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: azuredisk-csi-driver
  labels:
    kubeaddons.mesosphere.io/name: azuredisk-csi-driver
    kubeaddons.mesosphere.io/provides: csi-driver
  annotations:
    appversion.kubeaddons.mesosphere.io/azuredisk-csi-driver: "0.4.0"
    values.chart.helm.kubeaddons.mesosphere.io/azuredisk-csi-driver: "https://raw.githubusercontent.com/mesosphere/charts/94333f633ccb198574f55bf0618ea182c727657a/stable/azuredisk-csi-driver/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  namespace: kube-system
  cloudProvider:
    - name: azure
      enabled: true
    - name: aws
      enabled: false
  chartReference:
    chart: azuredisk-csi-driver
    repo: https://mesosphere.github.io/charts/stable
    version: 0.4.0
