apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: dex-k8s-authenticator
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: dex-k8s-authenticator
  annotations:
    appversion.kubeaddons.mesosphere.io/dex-k8s-authenticator: "v1.1.0"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/provides: ingresscontroller
  chartReference:
    chart: dex-k8s-authenticator
    repo: https://mesosphere.github.io/charts/staging
    version: 1.1.6
    values: |
      ---
      image:
        repository: mesosphere/dex-k8s-authenticator
        tag: v1.1.0-25-gdeba-mesosphere
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        path: /token
        hosts:
          - ""
      dexK8sAuthenticator:
        #logoUrl: http://<path-to-your-logo.png>
        #tlsCert: /path/to/dex-client.crt
        #tlsKey: /path/to/dex-client.key
        clusters:
        - name: kubernetes-cluster
          short_description: "Kubernetes cluster"
          description: "Kubernetes cluster authenticator"
          # client_secret: value is generated automatically via initContainers
          client_id: kube-apiserver
          issuer: https://dex-kubeaddons.kubeaddons.svc.cluster.local:8080/dex
          # This URI is just a placeholder and it will be replaced during initContainers
          # with a URL pointing to the traefik ingress public load balancer.
          redirect_uri: https://dex-k8s-authenticator-kubeaddons.kubeaddons.svc.cluster.local:5555/token/callback/kubernetes-cluster
      caCerts:
        enabled: true
        secrets:
        - name: dex-root-ca
          filename: dex-root-ca.crt
          value: cGxhY2Vob2xkZXIK # b64 "placeholder" this will be updated by initcontainers
      initContainers:
      - name: initialize-dka-config
        image: kubeaddons/addon-initializer:v0.0.2
        args: ["dexK8sAuthenticator"]
