---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: elasticsearchexporter
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: elasticsearchexporter
  annotations:
    appversion.kubeaddons.mesosphere.io/elasticsearchexporter: "1.0.2"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/name: elasticsearch
  chartReference:
    chart: stable/elasticsearch-exporter
    version: 1.3.1
    values: |
      ---
      es:
        uri: http://elasticsearch-kubeaddons-client:9200
      image:
        repository: justwatch/elasticsearch_exporter
        tag: 1.0.2
        pullPolicy: IfNotPresent
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
        metricsPort:
          name: metrics
