---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: elasticsearchexporter
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: stable/elasticsearch-exporter
    version: 1.3.0
    values: |
      ---
      es:
        uri: http://elasticsearch-kubeaddons-client:9200
      image:
        repository: justwatch/elasticsearch_exporter
        tag: 1.0.2
        pullPolicy: IfNotPresent
      serviceMonitor:
        enabled: true
        interval: 30s
