---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: flagger
  namespace: flagger
  labels:
    kubeaddons.mesosphere.io/name: flagger
  annotations:
    sidecar.istio.io/inject: "false"
    appversion.kubeaddons.mesosphere.io/flagger: "0.19.0"
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.19.0"
    docs.kubeaddons.mesosphere.io/flagger: "https://docs.flagger.app/"
    values.chart.helm.kubeaddons.mesosphere.io/flagger: "https://raw.githubusercontent.com/weaveworks/flagger/0.19.0/charts/flagger/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: istio
  chartReference:
    chart: flagger
    repo: https://gpaul.github.io/charts/staging
    version: 0.19.0
    values: |
      ---
      meshProvider: istio
      metricsServer: http://prometheus-kubeaddons-prom-prometheus.kubeaddons:9090
