---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: flagger-loadtester
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: flagger-loadtester
  annotations:
    appversion.kubeaddons.mesosphere.io/flagger-loadtester: "0.9.0"
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.9.0"
    docs.kubeaddons.mesosphere.io/flagger-loadtester: "https://github.com/weaveworks/flagger/tree/0.19.0/charts/loadtester"
    values.chart.helm.kubeaddons.mesosphere.io/flagger: "https://raw.githubusercontent.com/weaveworks/flagger/0.19.0/charts/loadtester/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: istio
  chartReference:
    chart: flagger-loadtester
    version: 0.9.0
    repo: https://gpaul.github.io/charts/staging
