---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: fluentbit
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: fluentbit
  annotations:
    appversion.kubeaddons.mesosphere.io/fluentbit: "1.2.1"
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  chartReference:
    chart: stable/fluent-bit
    version: 2.0.5
    values: |
      ---
      backend:
        es:
          host: elasticsearch-kubeaddons-client
          time_key: '@ts'
        type: es
      filter:
        mergeJSONLog: false
      input:
        tail:
          parser: cri
        systemd:
          enabled: true
          filters:
            systemdUnit: []
      metrics:
        enabled: true
        service:
          labels:
            servicemonitor.kubeaddons.mesosphere.io/path: "api__v1__metrics__prometheus"
      tolerations:
        - effect: NoSchedule
          operator: Exists
      extraEntries:
        input: |-
         Strip_Underscores true
      resources:
        limits:
          memory: 500Mi
        requests:
          # values extracted from a 1 output/1 input setup here:
          # https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/fluent-bit-daemonset-kafka-rest.yml
          # we double it for 1 output (es)/2 input (tail, systemd) as an approximation
          cpu: 200m
          memory: 200Mi
