apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: harbor
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: harbor
    kubeaddons.mesosphere.io/provides: harbor
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.1.0-1"
    appversion.kubeaddons.mesosphere.io/harbor: "0.1"
    values.chart.helm.kubeaddons.mesosphere.io/harbor: "https://raw.githubusercontent.com/mesosphere/charts/harbor/dev/staging/harbor/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  namespace: kube-system
  cloudProvider:
    - name: aws
      enabled: false
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: harbor
    repo: https://mesosphere.github.io/charts/staging
    version: 1.2.1
