---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kibana
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: stable/kibana
    values: |
      ---
      files:
        kibana.yml:
          ## Default Kibana configuration from kibana-docker.
          elasticsearch.url: http://elasticsearch-kubeaddons-client:9200
          ## Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
          server.basePath: /ops/portal/kibana
      serviceAccount:
        create: true
      service:
        type: ClusterIP
        externalPort: 5601
        internalPort: 5601
      resources:
        # need more cpu upon initialization, therefore burstable class
        limits:
          cpu: 1000m
        requests:
          cpu: 100m
