---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kommander
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kommander
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists.
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    appversion.kubeaddons.mesosphere.io/kommander: "1.50.0"
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.21
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/name: kubefed
