---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: kommander
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.116.17-1"
    appversion.kubeaddons.mesosphere.io/kommander: "1.116.17"
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
    values.chart.helm.kubeaddons.mesosphere.io/kommander: "https://raw.githubusercontent.com/mesosphere/charts/master/stable/kommander/values.yaml"
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
        kubeaddons.mesosphere.io/name: dex
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    # repo: https://mesosphere.github.io/charts/stable
    repo: https://mhrabovcin.github.io/charts-test
    version: 0.1.45
    values: |
      ---
      ingress:
        extraAnnotations:
          traefik.ingress.kubernetes.io/priority: "2"

      kommander-cluster-lifecycle:
        controller:
          containers:
            manager:
              image:
                repository: mhrabovcin/kommander-cluster-lifecycle-controller-manager
                tag: latest

        webhook:
          image:
            repository: mhrabovcin/kommander-cluster-lifecycle-webhook
            tag: latest

        utilityApiserver:
          image:
            repository: mhrabovcin/kommander-cluster-lifecycle-utility-apiserver
            tag: latest

        certificates:
          issuer:
            name: kubernetes-ca
            kind: ClusterIssuer
