---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: kommander
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.149.0-2"
    appversion.kubeaddons.mesosphere.io/kommander: "1.149.0"
    # remove this when we patch kommander image to make it configurable, right now it searches for this with an addon named kommander
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
    # update this values
    values.chart.helm.kubeaddons.mesosphere.io/kommander: "https://raw.githubusercontent.com/mesosphere/charts/master/stable/kommander/values.yaml"
    helmv2.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<=0.2.3\", \"strategy\": \"delete\"}]"
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://s12chung.github.io/mycharts/staging
    version: 0.2.4
    values: |
      ---
      kommander-cluster-lifecycle:
        certificates:
          issuer:
            name: kubernetes-ca
            kind: ClusterIssuer
