---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: kommander
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.149.0-1"
    appversion.kubeaddons.mesosphere.io/kommander: "1.149.45"
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
    values.chart.helm.kubeaddons.mesosphere.io/kommander: "https://raw.githubusercontent.com/mesosphere/charts/master/stable/kommander/values.yaml"
    helmv2.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<=0.1.22\", \"strategy\": \"delete\"}]"
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://mesosphere.github.io/charts/stable
    version: 0.2.9
    values: |
      ---
      ingress:
        extraAnnotations:
          traefik.ingress.kubernetes.io/priority: "2"

      kommander-cluster-lifecycle:
        certificates:
          issuer:
            name: kubernetes-ca
            kind: ClusterIssuer
