---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kommander
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    appversion.kubeaddons.mesosphere.io/kommander: "1.116.17"
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
    values.chart.helm.kubeaddons.mesosphere.io/kommander: "https://raw.githubusercontent.com/mesosphere/charts/master/stable/kommander/values.yaml"
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/name: cert-manager
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.37
    values: |
      ---
      ingress:
        extraAnnotations:
          traefik.ingress.kubernetes.io/priority: "2"

      kommander-cluster-lifecycle:
        certificates:
          issuer:
            name: kubernetes-ca
            kind: ClusterIssuer
