apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kudo
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kudo
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.7.4-1"
    appversion.kubeaddons.mesosphere.io/kudo: "0.7.4"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kudo
    repo: https://mesosphere.github.io/charts/staging
    version: 0.1.1
