---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: localvolumeprovisioner
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    repo: https://gpaul.github.io/charts/stable
    chart: localvolumeprovisioner
    version: 0.1.1
