---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: localvolumeprovisioner
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: localvolumeprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    appversion.kubeaddons.mesosphere.io/localvolumeprovisioner: "1.0"
    values.chart.helm.kubeaddons.mesosphere.io/localvolumeprovisioner: "https://raw.githubusercontent.com/mesosphere/charts/6c43b8ab10108fb1adba5c6dd10e800e5f1abdd0/stable/localvolumeprovisioner/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  namespace: kube-system 
  cloudProvider:
    - name: aws
      enabled: false
      values: |
        # Multiple storage classes can be defined here. This allows to, e.g.,
        # distinguish between different disk types.
        # For each entry a storage class '$name' and
        # a host folder '/mnt/$dirName' will be created. Volumes mounted to this
        # folder are made available in the storage class.
        storageclasses:
          - name: localvolumeprovisioner
            dirName: disks
            isDefault: false
            reclaimPolicy: Delete
            volumeBindingMode: WaitForFirstConsumer
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: localvolumeprovisioner
    repo: http://127.0.0.1:8080
    version: 0.5.0
