apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: metallb
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: metallb
    kubeaddons.mesosphere.io/provides: loadbalancer
    kubeaddons.mesosphere.io/cluster-scoped: true
  annotations:
    appversion.kubeaddons.mesosphere.io/metallb: "0.7.3"
    values.chart.helm.kubeaddons.mesosphere.io/metallb: "https://raw.githubusercontent.com/helm/charts/b0f9cb2d7af822e0031f632f2faa0cbb53167770/stable/metallb/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: docker
      enabled: true
      values: |
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 172.17.1.200-172.17.1.250
    - name: none
      enabled: true
      values: |
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            # configure addresses for your network
            addresses: []
  chartReference:
    chart: stable/metallb
    version: 0.9.5
    values: |
      ---
      controller:
        requests:
          cpu: 100m
          memory: 100Mi
      speaker:
        requests:
          cpu: 100m
          memory: 100Mi
