---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: opsportal
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: opsportal
  annotations:
    appversion.kubeaddons.mesosphere.io/opsportal: "1.0.0"
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: opsportal
    repo: https://mesosphere.github.io/charts/stable
    version: 0.0.1
    values: |
      ---
      # enable bearerproxy
      bearerproxy:
        enabled: true
