apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: opsportal
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: opsportal
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0-1"
    appversion.kubeaddons.mesosphere.io/opsportal: "1.0.0"
    endpoint.kubeaddons.mesosphere.io/opsportal: /ops/portal/
    values.chart.helm.kubeaddons.mesosphere.io/opsportal: "https://raw.githubusercontent.com/mesosphere/charts/6c43b8ab10108fb1adba5c6dd10e800e5f1abdd0/stable/opsportal/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: opsportal
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.9
    values: |
      ---
      bearerproxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      landing:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      opsportal:
        ingress:
          paths:
            # kubernetes-dashboard
            - backend:
                serviceName: bearerproxy
                servicePort: 9091
              path: /ops/portal/kubernetes
            # harbor
            - backend:
                serviceName: harbor
                servicePort: 443
              path: /ops/portal/harbor
            # kibana
            - backend:
                serviceName: kibana-kubeaddons
                servicePort: 5601
              path: /ops/portal/kibana
            # grafana
            - backend:
                serviceName: prometheus-kubeaddons-grafana
                servicePort: 3000
              path: /ops/portal/grafana
            # prometheus
            - backend:
                serviceName: prometheus-kubeaddons-prom-prometheus
                servicePort: 9090
              path: /ops/portal/prometheus
            # alertmanager
            - backend:
                serviceName: prometheus-kubeaddons-prom-alertmanager
                servicePort: 9093
              path: /ops/portal/alertmanager
            # traefik
            - backend:
                serviceName: traefik-kubeaddons-dashboard
                servicePort: 80
              path: /ops/portal/traefik
