---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: storageclasses
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: storageclasses
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    appversion.kubeaddons.mesosphere.io/storageclasses: "1.0"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  namespace: kube-system 
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: storageclasses
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.0
